{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6c4ad2c2-841f-4000-84af-3e0e6b5952da",
   "metadata": {},
   "outputs": [],
   "source": [
    "from math import radians, degrees, cos, sin, tan, atan, pi, sqrt\n",
    "import numpy as np\n",
    "\n",
    "from cosapp.systems import System\n",
    "from cosapp.ports import Port\n",
    "\n",
    "from pythonocc_helpers.create import (CreatePoint, CreateBezier, CreateControlPoint, CreateCurve, CreatePlane,\n",
    "                            CreateWire, CreateExtrusion, CreateVector, CreateTranslation, CreateEdge,\n",
    "                            CreateLine, CreateScaling, CreateCoordSystem, CreateRotation, CreateBSpline,\n",
    "                            CreateAxis, CreateTopology, CreateScaling, CreateCylinder, CreateSolid, CreateCircle, \n",
    "                            CreateFace, CreateBox, CreateShell, CreateUnsignedCoordSystem, CreateEllipse,\n",
    "                            CreateDirection, CreateArray1, CreateOCCList)\n",
    "from pythonocc_helpers.measure import MeasureCurve\n",
    "from pythonocc_helpers.measure.shape import bounds\n",
    "from pythonocc_helpers.explore import ExploreSubshapes\n",
    "from pythonocc_helpers.render import JupyterThreeJSRenderer\n",
    "from pythonocc_helpers.transform import Scale, Sweep, Translate, Rotate, Move, BooleanOperation\n",
    "\n",
    "from OCC.Core.gp import gp_Pnt, gp_GTrsf2d, gp_Ax2d, gp_Pnt2d, gp_Dir2d\n",
    "from OCC.Core.BRep import BRep_Tool\n",
    "from OCC.Core.BRepLib import breplib_BuildCurve3d, breplib_BuildCurves3d\n",
    "from OCC.Core.Geom import Geom_CylindricalSurface, Geom_Plane\n",
    "from OCC.Core.Geom2d import Geom2d_Ellipse\n",
    "from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_Transform, BRepBuilderAPI_MakeFace, BRepBuilderAPI_MakeEdge\n",
    "from OCC.Core.GeomAPI import GeomAPI_ProjectPointOnCurve\n",
    "from OCC.Core.BRepOffsetAPI import BRepOffsetAPI_MakeThickSolid"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d754478b-b43b-4fa9-8937-da8518f8b7db",
   "metadata": {},
   "outputs": [],
   "source": [
    "class GeomPort(Port):\n",
    "\n",
    "    def setup(self):\n",
    "        self.add_variable(\"visible\", True)\n",
    "        self.add_variable(\"shape\", None)\n",
    "    \n",
    "\n",
    "def face_from_wires(plane, *wires):\n",
    "    builder = BRepBuilderAPI_MakeFace(plane)  \n",
    "    for w in wires:\n",
    "        builder.Add(w)\n",
    "        \n",
    "    return builder.Shape()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fc0cce18-50f5-4150-b983-d6a0d2317538",
   "metadata": {},
   "outputs": [],
   "source": [
    "class ParametricBladeGeometry(System):\n",
    "    \n",
    "    def setup(self):\n",
    "        self.add_inward(\"inlet_angle\", 0., unit=\"deg\")\n",
    "        self.add_inward(\"exit_angle\", 0., unit=\"deg\")\n",
    "        self.add_inward(\"max_thickness_ratio\", 0.03, unit=\"\")\n",
    "        self.add_inward(\"max_thickness_position\", 0.3, unit=\"\")\n",
    "        \n",
    "        self.add_inward(\"height_over_chord\", 2., unit=\"\")\n",
    "        self.add_inward(\"swirl\", 0., unit=\"\")\n",
    "        \n",
    "        self.add_inward(\"tip_radius\", 0.1, unit=\"m\")\n",
    "        self.add_inward(\"hub_to_tip_ratio\", 0.1, unit=\"\")\n",
    "        self.add_inward(\"q_factor\", 1., unit=\"\")\n",
    "        \n",
    "        self.add_inward(\"leading_tension\", 10, unit=\"\")\n",
    "        self.add_inward(\"trailing_tension\", 10., unit=\"\")\n",
    "        \n",
    "        self.add_inward(\"stacking_parameter\", 0., unit=\"\")\n",
    "        self.add_inward(\"stacking_angle\", 0., unit=\"deg\")\n",
    "\n",
    "        self.add_outward(\"stagger_angle\", 0., unit=\"deg\")\n",
    "        self.add_outward(\"dimension\", np.empty(3), unit=\"m\")\n",
    "        self.add_outward(\"position\", np.empty(3), unit=\"m\")\n",
    "        self.add_outward(\"backbone\", None)\n",
    "        self.add_outward(\"geometry\", None)\n",
    "        \n",
    "    def compute(self):\n",
    "\n",
    "        hub_radius = self.tip_radius * self.hub_to_tip_ratio\n",
    "        mean_radius = self.tip_radius * (1. + self.hub_to_tip_ratio) / 2.\n",
    "        height = self.tip_radius - hub_radius\n",
    "        chord = height / self.height_over_chord\n",
    "\n",
    "        max_thickness = self.max_thickness_ratio * chord\n",
    "        self.stagger_angle = (radians(self.inlet_angle) + radians(self.exit_angle)) / 2.\n",
    "\n",
    "        xi = 0.\n",
    "        yi = 0.\n",
    "        xe = sin(self.stagger_angle)\n",
    "        ye = cos(self.stagger_angle)\n",
    "\n",
    "        tstart = self.leading_tension * np.r_[sin(radians(self.inlet_angle)), cos(radians(self.inlet_angle))]\n",
    "        tend = self.trailing_tension * np.r_[sin(radians(self.exit_angle)), cos(radians(self.exit_angle))]\n",
    "        backbone2d = CreateCurve.as_curve(CreateBSpline.from_points_interpolate_with_bounds_control(((xi, yi), (xe, ye)), tangents=(tstart, tend),  tol=1e-6, periodic=False, directions_only=False))\n",
    "        self.backbone = CreateCurve.from_2d(backbone2d, CreatePlane.xpy((0., 0., 0.)))\n",
    "\n",
    "        center2d = np.array(MeasureCurve.value(backbone2d, backbone2d.LastParameter() * self.max_thickness_position).Coord())\n",
    "        xebb, yebb = center2d\n",
    "        de = self.max_thickness_ratio\n",
    "        xemax1 = xebb - de * cos(self.stagger_angle) * 2. / 3.\n",
    "        yemax1 = yebb + de * sin(self.stagger_angle) * 2. / 3.\n",
    "        xemax2 = xebb + de * cos(self.stagger_angle) / 3.\n",
    "        yemax2 = yebb - de * sin(self.stagger_angle) / 3.\n",
    "\n",
    "        center2d2 = np.array(MeasureCurve.value(backbone2d, backbone2d.LastParameter() * self.stacking_parameter).Coord())\n",
    "        c1 = CreateBSpline.from_points_interpolate_with_bounds_control((np.array(((xe, ye), (xemax1, yemax1), (xi, yi), (xemax2, yemax2), (xe, ye))) - center2d2).tolist(), tangents=(-tend, tend),  \n",
    "                                                                    tol=1e-6, periodic=False, directions_only=False)\n",
    "        \n",
    "        \n",
    "        def scale_2d_profile(curve, f):\n",
    "            gtrsf = gp_GTrsf2d()\n",
    "            gtrsf.SetAffinity(gp_Ax2d(gp_Pnt2d(), gp_Dir2d(1., 0.)), f)\n",
    "\n",
    "            arr = CreateArray1.of_points([p for p in curve.Poles()])\n",
    "            for i in range(1, arr.Length()+1):\n",
    "                p = arr.Value(i)\n",
    "                p.SetXY(gtrsf.Transformed(p.XY()))\n",
    "                curve.SetPole(i, p)\n",
    "\n",
    "        scale_2d_profile(c1, chord)\n",
    "        \n",
    "        cyl1 = Geom_CylindricalSurface(CreateUnsignedCoordSystem.ox(), hub_radius)\n",
    "        proj1 = BRepBuilderAPI_MakeEdge(c1, cyl1).Shape();\n",
    "        breplib_BuildCurve3d(proj1)\n",
    "\n",
    "        cyl2 = Geom_CylindricalSurface(CreateUnsignedCoordSystem.ox(), mean_radius)\n",
    "        proj2 = BRepBuilderAPI_MakeEdge(Translate.from_vector(c1, (-radians(self.swirl) / 2., 0.), inplace=False), cyl2).Shape();\n",
    "        breplib_BuildCurve3d(proj2)\n",
    "\n",
    "        cyl3 = Geom_CylindricalSurface(CreateUnsignedCoordSystem.ox(), self.tip_radius)        \n",
    "        proj3 = BRepBuilderAPI_MakeEdge(Translate.from_vector(c1, (-radians(self.swirl), 0.), inplace=False), cyl3).Shape();\n",
    "        breplib_BuildCurve3d(proj3)\n",
    "        \n",
    "        segment = CreateLine.between_2_points(BRep_Tool.Curve(proj1)[0].Value(0.), BRep_Tool.Curve(proj3)[0].Value(0.))\n",
    "        sw = Sweep.profiles_along_path((proj1, proj2, proj3), segment, build_solid=True)\n",
    "\n",
    "        bbox = np.array(bounds(proj1))\n",
    "        rmin_box = max(sqrt(bbox[1]**2 + bbox[2]**2), sqrt(bbox[4]**2 + bbox[5]**2))\n",
    "        xmin_box = bbox[0]\n",
    "        hx_box = bbox[3] - bbox[0]\n",
    "        \n",
    "        self.position = np.r_[xmin_box, 0., 0.]\n",
    "        self.dimension = bbox[3:] - bbox[:3]\n",
    "\n",
    "        self.geometry = sw\n",
    "        # self.geometry = CreateTopology.make_compound(CreateTopology.make_edge(c1_3d), CreateTopology.make_edge(self.backbone))\n",
    "        # self.geometry = CreateTopology.make_compound(proj1, proj2, proj3)\n",
    "\n",
    "\n",
    "class CasingGeometry(System):\n",
    "    \n",
    "    def setup(self):\n",
    "        self.add_inward(\"blade_tip_radius\", 0.1, unit=\"m\")\n",
    "        self.add_inward(\"blade_hub_to_tip_ratio\", 0.3, unit=\"\")\n",
    "\n",
    "        self.add_inward(\"blade_dimension\", np.empty(3), unit=\"m\")\n",
    "        self.add_inward(\"blade_position\", np.empty(3), unit=\"m\")\n",
    "\n",
    "        self.add_inward(\"struts_width_ratio\", 0.05, unit=\"\")\n",
    "        self.add_inward(\"struts_min_width\", 0.005, unit=\"m\")\n",
    "        self.add_inward(\"struts_thickness_ratio\", 0.03, unit=\"\")\n",
    "        self.add_inward(\"struts_min_thickness\", 0.002, unit=\"m\")\n",
    "        self.add_inward(\"struts_clearance_ratio\", 0.05, unit=\"\")\n",
    "        self.add_inward(\"struts_min_clearance\", 0.005, unit=\"m\")\n",
    "        \n",
    "        self.add_inward(\"thickness_ratio\", 0.05, unit=\"\")\n",
    "        self.add_inward(\"min_thickness\", 0.008)\n",
    "\n",
    "        self.add_inward(\"clearance_ratio\", 0.01, unit=\"\")\n",
    "        self.add_inward(\"min_clearance\", 0.002, unit=\"m\")\n",
    "        \n",
    "        self.add_outward(\"width\", 0.1, unit=\"m\")\n",
    "        self.add_outward(\"height\", 0.1, unit=\"m\")\n",
    "        self.add_outward(\"geometry\", None)\n",
    "    \n",
    "    def compute(self):\n",
    "        clearance = max(self.clearance_ratio * self.blade_tip_radius, self.min_clearance)\n",
    "        thickness = max(self.thickness_ratio * self.blade_tip_radius, self.min_thickness)\n",
    "        size = self.width = self.height = self.blade_tip_radius + thickness + clearance\n",
    "        \n",
    "        struts_width = max(self.struts_width_ratio * self.blade_tip_radius, self.struts_min_width)\n",
    "        struts_thickness = max(self.struts_thickness_ratio * self.blade_tip_radius, self.struts_min_thickness)\n",
    "        struts_clearance = max(self.struts_clearance_ratio * self.blade_tip_radius, self.struts_min_clearance)\n",
    "        \n",
    "        x0 = self.blade_position[0]\n",
    "        e = self.blade_dimension[0] + struts_clearance + struts_thickness\n",
    "        L = l = size\n",
    "\n",
    "        pt1 = CreatePoint.as_point((x0 + e * 3. / 8, l, L))\n",
    "        pt2 = CreatePoint.as_point((x0 + e * 3. / 8, -l, L))\n",
    "        pt3 = CreatePoint.as_point((x0 + e * 3. / 8, -l, -L))\n",
    "        pt4 = CreatePoint.as_point((x0 + e * 3. / 8, l, -L))\n",
    "        w1 = CreateWire.from_points((pt1, pt2, pt3, pt4), auto_close=True)\n",
    "\n",
    "        c = CreateCircle.from_radius_and_center(self.blade_tip_radius + clearance, (x0, 0., 0.), CreateVector.ox())\n",
    "        w2 = CreateWire.from_element(c)\n",
    "\n",
    "        c2 = CreateCircle.from_radius_and_center(self.blade_tip_radius + clearance + 0.002, (x0, 0., 0.), CreateVector.ox())\n",
    "        w3 = CreateWire.from_element(c2)\n",
    "\n",
    "        f = face_from_wires(CreatePlane.ypz((x0, 0., 0.)), w2.Reversed(), w3)\n",
    "        casing = CreateExtrusion.surface(f, (e, 0., 0.))\n",
    "\n",
    "        c4 = CreateCircle.from_radius_and_center(self.blade_tip_radius + clearance + 0.002, (x0 + e * 3. / 8., 0., 0.), CreateVector.ox())\n",
    "        w4 = CreateWire.from_element(c4)\n",
    "\n",
    "        hole = CreateCircle.from_radius_and_center(0.004, (x0 + e * 3. / 8, l - 0.015, L - 0.015), CreateVector.ox())\n",
    "        wh = CreateWire.from_element(hole)\n",
    "        holes = []\n",
    "        for i in range(4):\n",
    "            trsf = BRepBuilderAPI_Transform(wh, CreateRotation.rotation_x(pi / 2. * i))\n",
    "            holes.append(trsf.Shape().Reversed())\n",
    "        \n",
    "        f2 = face_from_wires(CreatePlane.ypz((x0 + e * 3. / 8., 0., 0.)), w1, w4.Reversed(), *holes)\n",
    "        casing2 = CreateExtrusion.surface(f2, (e / 4., 0., 0.))\n",
    "        \n",
    "        x0 += e - struts_thickness\n",
    "        L = struts_thickness\n",
    "        l = struts_width\n",
    "        \n",
    "        def rectangle_on_cylinder(pos, dims, radius):\n",
    "            x, y = pos\n",
    "            l, L = dims\n",
    "            l /= radius\n",
    "            pt1 = CreatePoint.as_point((x + l / 2., y + L))\n",
    "            pt2 = CreatePoint.as_point((x - l / 2., y + L))\n",
    "            pt3 = CreatePoint.as_point((x - l / 2., y))\n",
    "            pt4 = CreatePoint.as_point((x + l / 2., y))\n",
    "        \n",
    "            l1 = CreateLine.between_2_points(pt1, pt2)\n",
    "            l2 = CreateLine.between_2_points(pt2, pt3)\n",
    "            l3 = CreateLine.between_2_points(pt3, pt4)\n",
    "            l4 = CreateLine.between_2_points(pt4, pt1)\n",
    "\n",
    "            from OCC.Core.BRepLib import breplib_BuildCurve3d, breplib_BuildCurves3d\n",
    "\n",
    "            cyl1 = Geom_CylindricalSurface(CreateUnsignedCoordSystem.ox(), radius)\n",
    "            proj1 = BRepBuilderAPI_MakeEdge(l1, cyl1).Shape();\n",
    "            breplib_BuildCurve3d(proj1)\n",
    "            proj2 = BRepBuilderAPI_MakeEdge(l2, cyl1).Shape();\n",
    "            breplib_BuildCurve3d(proj2)\n",
    "            proj3 = BRepBuilderAPI_MakeEdge(l3, cyl1).Shape();\n",
    "            breplib_BuildCurve3d(proj3)\n",
    "            proj4 = BRepBuilderAPI_MakeEdge(l4, cyl1).Shape();\n",
    "            breplib_BuildCurve3d(proj4)\n",
    "\n",
    "            w = CreateWire.from_elements((proj1, proj2, proj3, proj4))\n",
    "            \n",
    "            return w\n",
    "        \n",
    "        hub_radius = self.blade_hub_to_tip_ratio * self.blade_tip_radius\n",
    "        w1 = rectangle_on_cylinder((pi / 4., x0), (l, L), self.blade_tip_radius + clearance)\n",
    "        w2 = rectangle_on_cylinder((pi / 4., x0), (l, L), hub_radius)\n",
    "        \n",
    "        istart = hub_radius * cos(pi/4.)\n",
    "        iend = (self.blade_tip_radius + clearance) * cos(pi/4.)\n",
    "        strut = CreateLine.between_2_points((x0, istart, istart), (x0, iend, iend))\n",
    "        strut = Sweep.profiles_along_path((w1, w2), strut)\n",
    "        \n",
    "        struts = []\n",
    "        for i in range(4):\n",
    "            trsf = BRepBuilderAPI_Transform(strut, CreateRotation.rotation_x(pi / 2. * i))\n",
    "            struts.append(trsf.Shape())\n",
    "        \n",
    "        motor_plate = CreateCylinder.from_base_and_dir((x0, 0., 0.), CreateVector.as_vector((struts_thickness, 0., 0.)), hub_radius)\n",
    "        \n",
    "        self.geometry = CreateTopology.make_compound(casing, casing2, *struts, motor_plate)\n",
    "\n",
    "\n",
    "class RotorGeometry(System):\n",
    "    \n",
    "    def setup(self):\n",
    "        blade = self.add_child(ParametricBladeGeometry(\"blade\"), pulling={\"tip_radius\": \"tip_radius\", \"hub_to_tip_ratio\": \"hub_to_tip_ratio\", \"position\": \"blade_position\", \"dimension\": \"blade_dimension\"})\n",
    "\n",
    "        self.add_inward(\"count\", 2)\n",
    "        self.add_inward(\"thickness\", 1e-3, unit=\"m\")\n",
    "        self.add_outward(\"geometry\", None)\n",
    "\n",
    "    def compute(self):\n",
    "        blades = []\n",
    "        for i in range(self.count):\n",
    "            trsf = BRepBuilderAPI_Transform(self.blade.geometry, CreateRotation.rotation_x(2 * pi / self.count * i))\n",
    "            blades.append(trsf.Shape())\n",
    "        \n",
    "        x0 = self.blade_position[0]\n",
    "        e = self.blade_dimension[0]\n",
    "        th = self.thickness\n",
    "        moyeu = CreateCylinder.from_base_and_dir((x0, 0., 0.), CreateVector.as_vector((e, 0., 0.)), self.hub_to_tip_ratio * self.tip_radius - th)\n",
    "        \n",
    "        faces = ExploreSubshapes.get_faces(moyeu)\n",
    "        \n",
    "        to_remove = []\n",
    "        for f in faces:\n",
    "            g = Geom_Plane.DownCast(BRep_Tool.Surface(f))\n",
    "            if g and g.Location().X() > x0:\n",
    "                to_remove.append(f)\n",
    "                \n",
    "        to_remove = CreateOCCList.of_shapes(to_remove)\n",
    "\n",
    "        builder = BRepOffsetAPI_MakeThickSolid()\n",
    "        builder.MakeThickSolidByJoin(moyeu, to_remove, th, 1e-6)\n",
    "        hollowed_moyeu = builder.Shape()\n",
    "                \n",
    "        self.geometry = CreateTopology.make_compound(*blades, hollowed_moyeu)\n",
    "\n",
    "\n",
    "class FanGeometry(System):\n",
    "    \n",
    "    def setup(self):\n",
    "        rotor = self.add_child(RotorGeometry(\"rotor\"), pulling=[\"tip_radius\", \"hub_to_tip_ratio\"])\n",
    "        casing = self.add_child(CasingGeometry(\"casing\"))\n",
    "\n",
    "        self.connect(rotor.inwards, casing.inwards, {\"tip_radius\": \"blade_tip_radius\", \"hub_to_tip_ratio\": \"blade_hub_to_tip_ratio\"})\n",
    "        self.connect(rotor.outwards, casing.inwards, [\"blade_position\", \"blade_dimension\"])\n",
    "        \n",
    "        self.add_inward(\"factor\", 1., unit=\"\")\n",
    "\n",
    "        self.add_output(GeomPort, \"geometry\")\n",
    "        \n",
    "    def compute(self):\n",
    "        geom = CreateTopology.make_compound(self.rotor.geometry, self.casing.geometry)\n",
    "        self.geometry.shape = BRepBuilderAPI_Transform(geom, CreateScaling.from_factor(self.factor)).Shape()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "23e1afd4-942f-4f4f-90eb-43cea30b40b2",
   "metadata": {},
   "outputs": [],
   "source": [
    "fan = FanGeometry('fan')\n",
    "rotor = fan.rotor\n",
    "blade = rotor.blade\n",
    "casing = fan.casing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "90d20baa-296f-4b6a-b5c8-c84cf7408124",
   "metadata": {},
   "outputs": [],
   "source": [
    "render = JupyterThreeJSRenderer(view_size=(1800, 800), camera_target=(1., 1., 0.), camera_position=(1., 1., -2.))\n",
    "\n",
    "render_row = render.add_shape(fan.geometry.shape, uid=\"blade\", face_color=\"#156289\", opacity=1.)\n",
    "render_row.linear_deflection = 0.15\n",
    "render_row.angular_deflection = 0.15\n",
    "render.show();"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b61809f9-df8c-4d48-b3a3-25d984689abe",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "blade.height_over_chord = 1.5\n",
    "blade.q_factor = 1.\n",
    "blade.max_thickness_position = 0.3\n",
    "blade.max_thickness_ratio = 0.1\n",
    "blade.leading_tension = 1.\n",
    "blade.trailing_tension = 1.\n",
    "blade.inlet_angle = 80.\n",
    "blade.exit_angle = 40.\n",
    "blade.stacking_parameter = 0.\n",
    "blade.stacking_angle = 0.\n",
    "blade.swirl = 30.\n",
    "\n",
    "casing.thickness_ratio = 0.03\n",
    "casing.min_thickness = 0.002\n",
    "casing.clearance_ratio = 0.01\n",
    "casing.min_clearance = 0.002\n",
    "casing.struts_clearance_ratio = 0.05\n",
    "\n",
    "rotor.count = 6\n",
    "\n",
    "f = 1.\n",
    "fan.tip_radius = 0.1 / f\n",
    "fan.hub_to_tip_ratio = 0.35\n",
    "fan.factor = 10. * f\n",
    "\n",
    "fan.run_drivers()\n",
    "\n",
    "render.update_shape(fan.geometry.shape, uid=\"blade\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f5586a4b-49ca-4312-8e54-19725f149119",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "import ipywidgets as widgets\n",
    "\n",
    "slider = widgets.IntSlider(\n",
    "    value=7,\n",
    "    min=4,\n",
    "    max=13,\n",
    "    step=1,\n",
    "    description='Blade count:',\n",
    "    disabled=False,\n",
    "    continuous_update=False,\n",
    "    orientation='horizontal',\n",
    "    readout=True\n",
    ")\n",
    "\n",
    "def on_value_change(change):\n",
    "    rotor.count = change['new']\n",
    "    fan.run_drivers()\n",
    "    render.update_shape(fan.geometry.shape, uid=\"blade\");\n",
    "\n",
    "slider.observe(on_value_change, names='value')\n",
    "\n",
    "slider"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
